name: Build Marlin Firmwares

on:
  workflow_call:
    inputs:
      marlin_branch:
        description: Marlin branch to use
        type: string
        required: false
        default: bugfix-2.1.x
      build_env:
        description: The build 'environment' to use
        required: false
        type: string
        default: "NONE"
      build_obj:
        description: The build object, or resulting firmware
        type: string
        required: true
      config_dir:
        description: The directory holding your configs
        required: true
        type: string
      platformio_config:
        description: The path and filename of the file to use as platformio.ini
        required: false
        type: string
        default: ""
      prefix:
        description: tag prefix to use
        required: true
        type: string
        default: ""

jobs:
  build-marlin:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "tag=$(date +%m%d%Y-%H%M%S)" >> "$GITHUB_OUTPUT"
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install PlatformIO
        run: pip install platformio
      - name: Checkout Marlin
        run: git clone https://github.com/MarlinFirmware/Marlin
      - name: Copy configuration into place
        run: |
          cp -av ${{ inputs.config_dir }}/*.h Marlin/Marlin/
      - name: Clone and build Marlin ${{ inputs.config_dir }}
        run: |
          cd Marlin && pio run ${{ inputs.build_env != 'NONE' && format('-e {0}', inputs.build_env) || '' }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ inputs.prefix }}-${{ steps.date.outputs.tag }}
          title: ${{ inputs.prefix }}-${{ steps.date.outputs.tag }}
          files: |
            Marlin/.pio/build/${{ inputs.build_env != 'NONE' && inputs.build_env || " firmware.bin" }}${{ inputs.parent }}*
